### ISSUE TITLE
Add option to strictly check Content-Type

### ISSUE THREAD

**Issue by chasinglogic** [MikeCoder/MJsonViewer#1]
The method that you're using to determine if the content is JSON or not incorrectly picks up raw text responses as JSON from time to time. (such as build logs in my company's CI tool) I would love a "strict mode" option that only applies styling if Content-Type is set to application/json on the response.

I'd be willing to submit a PR for this if you would accept it but I'd rather not maintain a fork of this add-on.

**Comment by D0n9X1n** [comment]
Thanks for giving such a suggestion.

Any PR is acceptable.

I will fix it, few days later.

**Comment by D0n9X1n** [comment]
The new version has been uploaded to [Firefox Addons](https://addons.mozilla.org/).
It will be ready for downloading soon.

**Comment by chasinglogic** [comment]
Thanks for the quick turn around!
