### ISSUE TITLE
Class of <i> is modified on click

### ISSUE THREAD

**Issue by Invisi** [MikeCoder/MJsonViewer#10]
Hey there,
for some reason your extension modifies the class property of `<i>` on click.
Enabling strict mode in the settings doesn't change that either which is kinda annoying when dealing with Font Awesome as `fa fa-list` is turned to `fa Ca`.
My guess is that the culprit is somewhere inside [this code block](https://github.com/MikeCoder/MJsonViewer/blob/e785670d9633850a3e525b679a25af44190875c1/scripts/config.js#L89).

Minimal example: `<i class="ffff">Text</i>`
Result after clicking `Text`: `<i class="ffff Cfff">Text</i>`
[Video here](https://i.imgur.com/6zU0wum.gifv)

**Comment by D0n9X1n** [comment]
Thanks, try to upgrade to v3.14.

**Comment by Invisi** [comment]
Works perfectly, thanks! 👍
