### ISSUE TITLE
Some pages should not be json viewed automatically

### ISSUE THREAD

**Issue by xsnrg** [MikeCoder/MJsonViewer#11]
I think this falls under the "parse json even if the doc type is not json" feature, but some pages give a json view that should not.  The one that is currently giving me problems is the shopping cart page on Amazon.com.  Instead of displaying the order preview, it displays the json if the add-on is enabled.

Possible work-around is add the ability to not parse certain pages or domains?

Worth mentioning is I did toggle the option to strictly parse json doc type, and it also works around this, but disables other pages that do not have the proper doc type.

**Comment by D0n9X1n** [comment]
I can't reproduce the problem, can you give me more clues like screenshots or URLs?

For example, when I open the shopping cart page like this:

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/3142935/39929877-c4c64f5c-556b-11e8-9daf-bc047a23cc36.png">

Which part is wrong?

**Comment by xsnrg** [comment]
This is the page that goes into the json view:
https://www.amazon.com/gp/cart/view.html/ref=nav_cart

**Comment by D0n9X1n** [comment]
On my computer, this page works fine (just like the above image) with the addon enabled (strict mode off)...

Can you provide your addon version, firefox version and your OS version? A screenshot is also helpful.

**Comment by xsnrg** [comment]
Linux Fedora 27 with all current patches
Firefox 59.0.2
mjsonviewer 3.14
screenshot attached for that page.  I tried it with being logged out of amazon as well, same result.
![jsonview](https://user-images.githubusercontent.com/1186921/39930678-f5bb578a-5500-11e8-8f6e-409b089e2863.png)

**Comment by xsnrg** [comment]
with the add-on disabled:
![jsonoff](https://user-images.githubusercontent.com/1186921/39930811-52812da0-5501-11e8-957a-d871ed08d02c.png)


I also disabled all of my other addons in the case there was an incompatibility, but still get the json view

**Comment by D0n9X1n** [comment]
I get the point, working on it.

**Comment by D0n9X1n** [comment]
Upgrade to V3.15, it fixs the problem.

**Comment by xsnrg** [comment]
isJSON = handy!  And thank you for the quick fix.  I will test it soon and report back/close if it looks good.

**Comment by xsnrg** [comment]
Looks great!  Thanks again.
