### ISSUE TITLE
Accept a relaxed JSON syntax

### ISSUE THREAD

**Issue by mgouget** [MikeCoder/MJsonViewer#12]
Hello Mike,

Sometime, web sites (such as Airbnb.com for example) try to minimize the size of a JSON response by avoiding to quote keys *and* values when that does not create an ambiguity.
For example, I can get:

`{ available: true,
       date: '2019-03-12',
       closed_to_arrival: false,
       subtype_or_reservation_status: 'available',
       subtype: null,
       type: 'available',
       length_of_stay_promotion: null }`

MJsonViewer (rightfully) flags an error, but the net result is that the viewer can't be used on such a file!
Is there a possibility (such as a flag or a preference) to accept such a relaxed syntax?

Cheers,

Michel

**Comment by D0n9X1n** [comment]
Sure, will in development, thanks.
