### ISSUE TITLE
Extension being used in non-JSON pages

### ISSUE THREAD

**Issue by guidop91** [MikeCoder/MJsonViewer#14]
I was going through the old issues and noticed issue #11 described something practically the same as this. I also saw that you solved the problem in a really fast timeframe, which makes me appreciate this extension even more. I find it hard to use another extension for JSON, it is even an additional reason for me to use Firefox. 

Ok to my point, I discovered a while ago that going to [Pocket](https://getpocket.com) renders it in JSON form, which shouldn't be the case. I can only imagine that something done since that time made it break once more. 

Here's a screenshot of what I'm seeing: 

![Screen Shot 2022-04-07 at 2 49 04 PM](https://user-images.githubusercontent.com/29293078/162275440-77a370b7-6231-4e68-96a7-db46f87d87cf.png)

My details:

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:98.0) Gecko/20100101 Firefox/98.0

Please let me know if you need more information.

**Comment by D0n9X1n** [comment]
Hi, do you enable the strict mode? You can enable the strict mode by checking the highlight checkbox.
![image](https://user-images.githubusercontent.com/3142935/162346671-66c32a76-3701-49f4-9efa-852138a58c5e.png)

If problem exsits, could you also provide the information in console? Here is the instruction:
1. Press F12 on the page you see the unexpected result.
2. Select console and provide screenshot like:
![image](https://user-images.githubusercontent.com/3142935/162346844-5a6bc43f-b6a5-457d-81d8-861141c5f2f4.png)
