### ISSUE TITLE
Alternative Content-Types are not supported (e.g. application/hal+json)

### ISSUE THREAD

**Issue by sabi0** [MikeCoder/MJsonViewer#3]
Even with "Strict mode" disabled I still get browser prompt to download a file when I try to open application/hal+json resource.
So currently I have to use another add-on to override Content-Type for JSON: https://addons.mozilla.org/en-US/firefox/addon/json-content-type-override/ 

It would be nice if MJsonViewer supported such Content-Types natively.
(See [JSONovich](https://addons.mozilla.org/en-US/firefox/addon/jsonovich/) for some other JSON Content-Types)

**Comment by D0n9X1n** [comment]
Can you provide some urls for testing?

**Comment by sabi0** [comment]
Sorry, these are internal services.
Here is a sample response dump from browser Network console if that helps.
```
Date: Fri, 01 Dec 2017 09:47:16 GMT
Server: Apache
Pragma: No-cache
Cache-Control: no-cache
Expires: Thu, 01 Jan 1970 01:00:00 CET
Transfer-Encoding: chunked
Content-Type: application/hal+json;charset=UTF-8

{"_links":{"self":{"href":"http://..."},"applications":{"href":"http://..."}}}
```

The resource is secured if that matters. I.e. browser first receives HTTP 401 response, then repeats the request with proper Authorization header and finally gets HTTP 200 with JSON content.

**Comment by D0n9X1n** [comment]
I get it. Working in progress.

**Comment by D0n9X1n** [comment]
The new version has been uploaded, waiting for the validating.

**Comment by sabi0** [comment]
Is the new permission (Access browser activity during navigation) required to access response content type?

**Comment by D0n9X1n** [comment]
Yes, if you don't use the new permission, the response header will be read-only. Here I write two permissions to ask for the permission (webNavigation and webRequest). Actually, any one of them is enough, I write them both(according to the two plugins you mentioned) just in case.

**Comment by sabi0** [comment]
But why would you need to change the response header?
I thought MJsonViewer could just intercept `application/hal+json` response the same way as it intercepts `application/json`.

json-content-type-override add-on needs to modify the response header so that other add-ons (e.g. old MJsonViewer) see the response as `application/json`.

**Comment by D0n9X1n** [comment]
Get it. It's really a better way to solve this. It will be fixed later.

**Comment by D0n9X1n** [comment]
It seems impossible to add support to a new contentType. Like `application/hal+json`, the Firefox will treat it as type `hal`:
> ![image](https://user-images.githubusercontent.com/3142935/33603097-6fe4dcf6-d9ec-11e7-806b-7fbd85deb964.png)

Which I can't do anything to stop the download dialog(Even in the entry point `document_start`).

I try to find how [JSONovich](https://github.com/JSONovich/jsonovich/blob/ee5f0ee7af6f3b896b97b523370306abe539e1ff/src/background.js#L206) deals with this issue. It appends `application/json` to the response header.

And [json-lite](https://github.com/lauriro/json-lite) which don't modify the header can't deal with the `application/hal+json` response.

So, I think it is the only way(Or can you give some plugins which support  unknown contentTypes).

And if you open the Del Tools, the response header is still  `application/hal+json`. The modified header is only to cheat the rendering engine.
> ![image](https://user-images.githubusercontent.com/3142935/33603543-d31a719a-d9ed-11e7-95ba-aaa32fd7d2c3.png)

**Comment by sabi0** [comment]
I see.
Sorry I am not that much familiar with Firefox add-ons "internal kitchen". And it seemed to me that changing the content type header wasn't necessary.

But how do you intercept rendering of `application/json` responses? Do you register some 'handler' for 'json' type? I can't find it in the add-on.
Otherwise, add-on must be called for every page. And you'd need to signal somehow to the browser that it shouldn't ask for saving `application/json` responses to disk. I can't find that "signal" either.

P.S. It looks like 'strict' mode is broken in 2.1 When it's enabled I see blank yellow page for `application/hal+json` responses. You should probably change this pattern
```
/[+\/]json$/i.test(document.contentType)
```
to something like
```
/[+\/]json(;.*)?$/i.test(document.contentType)
```
to also allow `.../json;charset=...`
Maybe this is also the trick to make `application/hal+json` work out of the box? (without changing the response header)

**Comment by D0n9X1n** [comment]
Actually, I don't intercept the responses. This plugin has a functional script([mjsonviewr.js](https://github.com/MikeCoder/MJsonViewer/blob/c8749b3692e0d1809e293a2e02b9985dea8d7ca8/manifest.json#L29)) which will be called when the total page has been loaded and a background script([background.js](https://github.com/MikeCoder/MJsonViewer/blob/c8749b3692e0d1809e293a2e02b9985dea8d7ca8/manifest.json#L35)) which will always run. 

When the response get(before the rendering engine act), the background.js will append a json header to the response, then the browser will deal with the response as a json. Then, at the end of loading the page, the functional script(mjsonviewer.js) will be called to render the json string.

BTW: Nice bug catch.

**Comment by sabi0** [comment]
Without your add-on Firefox shows a prompt to save json response to disk. And when the add-on is installed the prompt does not appear anymore.
How does Firefox know that the add-on "handled" the response and it should not be downloaded?

And if the add-on is called for every response (and has a chance to "handle" it) why does Firefox still suggest to download 'hal' response? Shouldn't the add-on have "handled" it in the same way as it "handles" 'json' responses?

**Comment by D0n9X1n** [comment]
The code is [Here](https://github.com/MikeCoder/MJsonViewer/blob/c8749b3692e0d1809e293a2e02b9985dea8d7ca8/background.js#L33), I only change the response header when it contains a `json`.

**Comment by sabi0** [comment]
Yes, I saw background.js
I still don't get however why `application/json` and `application/hal+json` are handled differently?

The regexp in mjsonviewer.js matches both these content types (it allows either '+' or '/' before 'json').
Without the add-on Firefox shows save prompt for both `application/json` and `application/hal+json`.
So why does it still show the prompt for `application/hal+json` after the add-on is installed but does not show it for `application/json` anymore?

Here is a screenshot from Firefox console:
![image](https://user-images.githubusercontent.com/11509875/33613182-409ecc8a-d9d4-11e7-84de-d729b837ddf5.png)
And as far as I understand it means that `application/hal+json` should work fine without changing the response header.
What did I miss?

**Comment by D0n9X1n** [comment]
May the rendering process of the firefox will help.
```
Web Site ===> Browser ===> Firefox Event Dispatcher ===> MJsonViewer
                       |               
             background.js act here
```

If the response with `application/hal+json`, the Firefox Event Dispatcher will deal with it as a `hal` type(you can see the image below)
> ![image](https://user-images.githubusercontent.com/3142935/33603097-6fe4dcf6-d9ec-11e7-806b-7fbd85deb964.png)

So, the background.js is the key.

**Comment by sabi0** [comment]
So it's Event Dispatcher who shows the download prompt for 'hal'? Why doesn't it show it for 'json' when the add-on is installed?

Isn't it rather like this?
```
Web Site ===> Browser ===> Firefox Event Dispatcher ===> MJsonViewer ===> Download prompt
```
But then the add-on should be able to "intercept" 'hal' the same way it intercepts 'json'. Am I wrong?

**Comment by D0n9X1n** [comment]
Because display `json`(like html, xml .etc) type is the default action.

It will like this:
```
                                                    ==>  Page Render ==> MJsonViewer
Web Site ==> Browser ==> Firefox Event Dispatcher 
                                                    ==>  Download prompt
```

Yes, in background.js, you can intercept every response.

**Comment by sabi0** [comment]
You are right.
I believed I'd also get download prompt for 'json' if MJsonViewer is not installed. But those were actually for `application/hal+json`.
Sorry for bothering you with all these questions.
