### ISSUE TITLE
[Feature request] Option to hide items and bytes counters

### ISSUE THREAD

**Issue by sabi0** [MikeCoder/MJsonViewer#4]
I don't really need them. And in data-intensive JSONs they do clutter the view unnecessarily.

**Comment by D0n9X1n** [comment]
The new version has been uploaded, waiting for the validating.

**Comment by sabi0** [comment]
The new option works great. Thanks!

**Comment by sabi0** [comment]
It would be nice to have the information available in the popup hint when hovering the folding triangle:
![image](https://user-images.githubusercontent.com/11509875/33995141-4e02c6dc-e0dd-11e7-981b-d9457f4fca33.png)

**Comment by D0n9X1n** [comment]
Looks good to me.

**Comment by D0n9X1n** [comment]
It has been done in v3.7.
