### ISSUE TITLE
[Bug] Version 3.1 does not display (large?) JSON properly

### ISSUE THREAD

**Issue by sabi0** [MikeCoder/MJsonViewer#6]
After MJsonViewer was updated (I now have version 3.1) some JSONs are not displayed properly.
Sometimes I only get an inner piece of JSON structure. Sometimes it's a completely blank page:
![image](https://user-images.githubusercontent.com/11509875/33941535-4af2c516-e013-11e7-9c67-f3bfdf8f9645.png)

Here is an example JSON displayed on the above screenshot: https://pastebin.com/rSrpPeyA

Deleting a few lines from the file makes it show up correctly. So it's apparently some boundary issue.
Either on number of lines or the file size.
The problem is present when the file contains 399 lines and 10965 bytes. But as soon as I change it to 390 lines and 10722 bytes the problem disappears.

**Comment by D0n9X1n** [comment]
Check V3.2.

**Comment by sabi0** [comment]
It works fine in 3.5
