### ISSUE TITLE
[Feature request] Highlight the hovered border

### ISSUE THREAD

**Issue by sabi0** [MikeCoder/MJsonViewer#7]
Highlighting a JSON element "indentation guide" on hover would help to trace to where it begins.
This is particularly useful for long elements. Especially the ones that span multiple pages.

Here is a mockup of what I mean:
![image](https://user-images.githubusercontent.com/11509875/33996091-626bdeee-e0e0-11e7-88d4-c7909bf86eeb.png)

It would be also nice to be able to click the "indentation guide" to collapse the element.

**Comment by D0n9X1n** [comment]
Looks Good. Will support next version.

**Comment by D0n9X1n** [comment]
Now, you can highlight the block on v3.6.

First, you should enble this feature in `about:addons` page.

Then click on the block which you need to highlight. It looks like:

![image](https://user-images.githubusercontent.com/3142935/34091211-25dc2d48-e3f7-11e7-8f27-fa4dc202dc34.png)

**Comment by sabi0** [comment]
This is cool! Thank you.
But please allow a few pixels "tolerance" if possible.
Currently clicking when mouse pointer is like this toggles the "wrong" line:
![image](https://user-images.githubusercontent.com/11509875/34097086-12cfd3ea-e3d8-11e7-9691-fa796d97fac8.png)

**Comment by D0n9X1n** [comment]
Now, it has more space in the area in v3.7.

**Comment by sabi0** [comment]
I've updated the add-on to version 3.7.
Distance between the "indentation guides" has increased indeed. But when I click _a few pixels to the left_ of some "guide" another "guide" is highlighted. Just like shown on the screenshot in my previous comment.
