### ISSUE TITLE
[Bug] Links are not clickable

### ISSUE THREAD

**Issue by sabi0** [MikeCoder/MJsonViewer#9]
Links are not clickable anymore since v3.5 (still not clickable in v3.9)

I guess it might be the consequence of the fix for this problem:
https://github.com/MikeCoder/MJsonViewer/issues/5#issuecomment-351387970

Anyway, I cannot use the add-on ever since.

**Comment by sabi0** [comment]
I don't get it. You intentionally made links not clickable? Why??

**Comment by D0n9X1n** [comment]
v3.13 fix this.
